#!/usr/bin/env python3
"""Generate supabase/products_seed.sql from the current assets.html/minecraft.html
product cards. This intentionally duplicates the tiny slugify()/parse_catalog()
regexes from build.py (rather than importing build.py, which has import-time side
effects: it reads every page, rewrites catalog.js, and writes a single-file bundle).
Keeping the same regex logic verbatim guarantees seeded slugs match catalog.js's
ids byte-for-byte.

Run from the repo root: python3 scripts/generate_products_sql.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).parent.parent


def slugify(text: str) -> str:
    return re.sub(r'[^a-z0-9]+', '-', text.lower()).strip('-')


def humanize(slug: str) -> str:
    return slug.replace('-', ' ').replace(' ui', ' UI').title().replace(' And ', ' & ').replace('Ui', 'UI').replace('Vfx', 'VFX')


def parse_catalog(html: str, platform: str, page: str):
    items = []
    for block in re.findall(r'<article class="product".*?</article>', html, re.S):
        cat_m = re.search(r'data-cat="([^"]+)"', block)
        img_m = re.search(r"background-image:url\('([^']+)'\)", block)
        title_m = re.search(r'<h3[^>]*>(.*?)</h3>', block, re.S)
        price_m = re.search(r'p-price">(.*?)</span>', block, re.S)
        catlabel_m = re.search(r'data-catlabel="([^"]+)"', block)
        desc_m = re.search(r'p-sum">(.*?)</p>', block, re.S)
        price_num_m = re.search(r'data-price="([0-9.]+)"', block)
        was_m = re.search(r'data-was="([0-9.]+)"', block)
        subcat_m = re.search(r'data-subcat="([^"]+)"', block)
        reviews_m = re.search(r'data-reviews="([0-9]+)"', block)
        rating_m = re.search(r'data-rating="([0-9.]+)"', block)
        free_m = 'data-free="yes"' in block
        if not (title_m and price_m):
            continue
        if free_m:
            # Free items ("Join Discord to unlock") aren't real Stripe products.
            continue
        unesc = lambda s: s.replace('&amp;', '&').strip()
        cat_label = unesc(catlabel_m.group(1)) if catlabel_m else (humanize(cat_m.group(1)) if cat_m else '')
        title = unesc(title_m.group(1))
        items.append({
            'id': slugify(title),
            'title': title,
            'priceNum': float(price_num_m.group(1)) if price_num_m else 0,
            'image': img_m.group(1) if img_m else '',
            'cat': cat_label,
            'desc': unesc(desc_m.group(1)) if desc_m else '',
            'resell': 'data-resell="yes"' in block,
            'was': float(was_m.group(1)) if was_m else 0,
            'subcat': subcat_m.group(1) if subcat_m else '',
            'reviews': int(reviews_m.group(1)) if reviews_m else 0,
            'rating': float(rating_m.group(1)) if rating_m else 0,
            'platform': platform,
            'page': page,
        })
    return items


def sql_str(s):
    if s is None:
        return 'null'
    return "'" + str(s).replace("'", "''") + "'"


def sql_num(n):
    return 'null' if n is None else str(n)


def main():
    assets_html = (ROOT / 'assets.html').read_text()
    minecraft_html = (ROOT / 'minecraft.html').read_text()

    catalog = parse_catalog(assets_html, 'Roblox', 'assets.html') + \
        parse_catalog(minecraft_html, 'Minecraft', 'minecraft.html')

    seen = set()
    lines = [
        '-- Generated by scripts/generate_products_sql.py -- do not hand-edit.',
        '-- Run this once in Supabase Dashboard -> SQL Editor, after products.sql.',
        '',
    ]
    for item in catalog:
        slug = item['id']
        if slug in seen:
            print(f'WARNING: duplicate slug "{slug}" ({item["title"]}) -- skipping duplicate')
            continue
        seen.add(slug)
        was = item['was'] if item['was'] else None
        lines.append(
            "insert into public.products "
            "(slug, title, price_usd, resell_available, was_price, image, description, "
            "cat, subcat, platform, page, reviews_count, rating) values "
            f"({sql_str(slug)}, {sql_str(item['title'])}, {sql_num(item['priceNum'])}, "
            f"{str(item['resell']).lower()}, {sql_num(was)}, {sql_str(item['image'])}, "
            f"{sql_str(item['desc'])}, {sql_str(item['cat'])}, {sql_str(item['subcat']) if item['subcat'] else 'null'}, "
            f"{sql_str(item['platform'])}, {sql_str(item['page'])}, {item['reviews']}, {item['rating']}) "
            "on conflict (slug) do nothing;"
        )

    out_path = ROOT / 'supabase' / 'products_seed.sql'
    out_path.write_text('\n'.join(lines) + '\n')
    print(f'Wrote {out_path} ({len(seen)} products)')


if __name__ == '__main__':
    main()
